env:
  game: 'BreakoutNoFrameskip-v4'
  stack_len: 2
  seed: 1314121
  solved_criteria: 30
  q_threhold: 100
  pomdp: False
  pomdp_type: 'flickering'  # flickering|delete_dim
  # pomdp_mask: [1, 0, 1, 0]  # this mask is chosen depended on the hiding dimensions and the observation shape of the env (i.e. 0)
  pomdp_prob: 0.7
  mode: 0

model:
  model_file: 'breakout_dqncnn.pt'
  kernel_num: 32
  hidden_dim: 512
  enable_dueling: False
  dueling_type: 'avg'
  dtype: 'torch.float32'

memory:
  size: 200000
  a: 0.6
  b: 0.4

env_type: 'atari'
model_type: 'dqn_cnn'
memory_type: 'random'
agent_type: 'dqn'
mode: 'train'  # train|test
value_criteria: 'smooth_l1_loss'
optimizer: 'RMSprop'
train_visualize: False
retrain: True
solved_stop: True

random_eps: 0
steps: 1000000
learn_start: 50000
gamma: 0.99
# clip_grad: 1.0
lr: 0.00025
lr_decay: False
eps_start: 1.0
eps_decay: 500000
eps_end: 0.1
prog_freq: 10000
target_model_update: 10000
batch_size: 32
train_interval: 4
log_window_size: 100
test_nepisodes: 1
log_step_interval: 100
log_episode_interval: 10
use_tensorboard: False
bootstrap_type: 'double_q'  # learn_q|target_q|double_q