env:
  game: 'Breakout-ram-v0'
  stack_len: 1
  seed: 1314121
  solved_criteria: 300
  q_threhold: 300
  pomdp: False
  pomdp_type: 'flickering'  # flickering|delete_dim
  # pomdp_mask: [1, 0, 1, 0]  # this mask is chosen depended on the hiding dimensions and the observation shape of the env (i.e. 0)
  pomdp_prob: 0.7
  mode: 0

model:
  model_file: 'breakout_dqn.pt'
  hidden_dim: 256
  enable_dueling: False
  dueling_type: 'avg'
  dtype: 'torch.float32'

memory:
  size: 40000
  a: 0.6
  b: 0.4

env_type: 'gym'
model_type: 'dqn_fc'
memory_type: 'random'
agent_type: 'dqn'
mode: 'train'  # train|test
value_criteria: 'smooth_l1_loss'
optimizer: 'Adam'
train_visualize: False
retrain: True
solved_stop: True

random_eps: 0
episodes: 5000
steps: 22000000  # max possible steps
learn_start: 10000
gamma: 0.99
# clip_grad: 1.0
lr: 0.0005
lr_decay: False
eps_start: 1.0
eps_decay: 5000
eps_end: 0.05
prog_freq: 50
target_model_update: 2000
batch_size: 16
train_interval: 2
log_window_size: 100
test_nepisodes: 1
log_step_interval: 1000
log_episode_interval: 10
use_tensorboard: False
bootstrap_type: 'double_q'  # learn_q|target_q|double_q